import { FormEvent, useEffect, useMemo, useState } from "react";
import {
  BarChart3,
  Building2,
  CalendarDays,
  ClipboardList,
  FileCheck2,
  FileText,
  LoaderCircle,
  Plus,
  ReceiptText,
  Search,
  Users,
  WalletCards,
} from "lucide-react";
import { Link } from "react-router-dom";
import AdminWorkspace from "@/components/admin/AdminWorkspace";
import { isSupabaseConfigured, supabase } from "@/lib/supabase";

export type CrmModuleKey = "customers" | "quotes" | "finance" | "contracts" | "receipts" | "availability" | "statistics" | "company";

type Customer = { id: string; name: string; document_number?: string | null; phone?: string | null; created_at: string };
type Appointment = { id: string; event_date: string; start_time?: string | null; end_time?: string | null; status: string; total_amount?: number | null; customers?: Customer | Customer[] | null; appointment_items?: { quantity: number; products?: { name?: string } | { name?: string }[] | null }[] };
type Quote = { id: string; title: string; event_date?: string | null; total_amount?: number | null; status: string; valid_until?: string | null; customers?: Customer | Customer[] | null };
type FinancialEntry = { id: string; description: string; category?: string | null; entry_type: "income" | "expense"; amount: number; due_date?: string | null; paid_at?: string | null; status: "pending" | "paid" | "overdue" | "cancelled" };
type Contract = { id: string; title: string; status: "draft" | "sent" | "signed" | "cancelled"; signed_at?: string | null; created_at: string; customers?: Customer | Customer[] | null };
type Receipt = { id: string; receipt_number: string; amount: number; issued_at: string; customers?: Customer | Customer[] | null };
type AvailabilityBlock = { id: string; title: string; start_at: string; end_at: string; block_type: "unavailable" | "maintenance" | "internal" };
type Notice = { tone: "success" | "error"; message: string } | null;

const moduleMeta: Record<CrmModuleKey, { eyebrow: string; title: string; description: string; icon: typeof Users }> = {
  customers: { eyebrow: "Relacionamento", title: "Clientes", description: "Centralize os dados de contato e acompanhe quem já alugou com a Monteiro.", icon: Users },
  quotes: { eyebrow: "Comercial", title: "Orçamentos", description: "Registre propostas, acompanhe a validade e avance somente as oportunidades aprovadas.", icon: FileText },
  finance: { eyebrow: "Financeiro", title: "Financeiro", description: "Controle entradas, saídas e contas que ainda precisam de atenção.", icon: WalletCards },
  contracts: { eyebrow: "Documentos", title: "Contratos", description: "Organize contratos por cliente e acompanhe cada assinatura.", icon: FileCheck2 },
  receipts: { eyebrow: "Documentos", title: "Recibos", description: "Registre os comprovantes emitidos e mantenha o histórico financeiro organizado.", icon: ReceiptText },
  availability: { eyebrow: "Planejamento", title: "Disponibilidade", description: "Veja os eventos confirmados e bloqueie períodos para manutenção ou operação interna.", icon: CalendarDays },
  statistics: { eyebrow: "Inteligência", title: "Estatísticas", description: "Acompanhe os principais números da operação para decidir com mais clareza.", icon: BarChart3 },
  company: { eyebrow: "Configurações", title: "Empresa", description: "Mantenha os dados usados nos documentos e no atendimento sempre atualizados.", icon: Building2 },
};

function getCustomer(value: Appointment["customers"]) {
  return Array.isArray(value) ? value[0] : value;
}

function formatMoney(value?: number | null) {
  return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(value || 0));
}

function formatDate(value?: string | null) {
  if (!value) return "A definir";
  return new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "2-digit", year: "numeric" }).format(new Date(`${value.slice(0, 10)}T12:00:00`));
}

function getErrorMessage(error: unknown) {
  return error instanceof Error ? error.message : "Ocorreu um erro inesperado.";
}

function EmptyState({ icon: Icon, title, description }: { icon: typeof Users; title: string; description: string }) {
  return <div className="grid place-items-center rounded-3xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-cyan-50 text-[#00BFFF]"><Icon size={27} /></span><h2 className="mt-5 text-xl font-black">{title}</h2><p className="mt-2 max-w-md text-sm leading-relaxed text-slate-500">{description}</p></div>;
}

function ModuleHeader({ module, action, children }: { module: CrmModuleKey; action?: React.ReactNode; children?: React.ReactNode }) {
  const meta = moduleMeta[module];
  const Icon = meta.icon;
  return <><div className="mt-5 flex flex-wrap items-center justify-between gap-4"><Link to="/admin" className="text-sm font-bold text-slate-500 transition hover:text-[#008fc0]">← Voltar à visão geral</Link><div className="flex items-center gap-3">{children}{action}</div></div><header className="mt-9 flex items-start gap-4"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-slate-950 text-cyan-300 shadow-lg"><Icon size={26} /></span><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#00BFFF]">{meta.eyebrow}</p><h1 className="mt-2 text-4xl font-black tracking-[-.045em]">{meta.title}</h1><p className="mt-3 max-w-2xl leading-relaxed text-slate-500">{meta.description}</p></div></header></>;
}

function Panel({ children, className = "" }: { children: React.ReactNode; className?: string }) {
  return <section className={`rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6 ${className}`}>{children}</section>;
}

function TextInput({ label, ...props }: { label: string } & React.InputHTMLAttributes<HTMLInputElement>) {
  return <label className="block text-sm font-bold text-slate-700"><span>{label}</span><input {...props} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 font-medium outline-none transition focus:border-cyan-400 focus:ring-2 focus:ring-cyan-100" /></label>;
}

function SelectInput({ label, children, ...props }: { label: string; children: React.ReactNode } & React.SelectHTMLAttributes<HTMLSelectElement>) {
  return <label className="block text-sm font-bold text-slate-700"><span>{label}</span><select {...props} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 font-medium outline-none transition focus:border-cyan-400 focus:ring-2 focus:ring-cyan-100">{children}</select></label>;
}

function SubmitButton({ pending, children }: { pending: boolean; children: React.ReactNode }) {
  return <button disabled={pending} type="submit" className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white transition hover:bg-slate-800 disabled:cursor-wait disabled:opacity-60">{pending && <LoaderCircle size={17} className="animate-spin" />}{children}</button>;
}

function NoticeBanner({ notice }: { notice: Notice }) {
  if (!notice) return null;
  return <div className={`mt-6 rounded-2xl border px-4 py-3 text-sm font-semibold ${notice.tone === "success" ? "border-emerald-100 bg-emerald-50 text-emerald-800" : "border-rose-100 bg-rose-50 text-rose-800"}`}>{notice.message}</div>;
}

function CustomersModule() {
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [query, setQuery] = useState("");
  const [openForm, setOpenForm] = useState(false);
  const [pending, setPending] = useState(false);
  const [notice, setNotice] = useState<Notice>(null);

  const load = async () => {
    const { data, error } = await supabase!.from("customers").select("id, name, document_number, phone, created_at").order("created_at", { ascending: false });
    if (error) throw error;
    setCustomers((data || []) as Customer[]);
  };

  useEffect(() => { load().catch((error) => setNotice({ tone: "error", message: `Não foi possível carregar os clientes: ${getErrorMessage(error)}` })); }, []);
  const visible = useMemo(() => { const value = query.trim().toLocaleLowerCase("pt-BR"); return customers.filter((customer) => !value || [customer.name, customer.document_number, customer.phone].filter(Boolean).join(" ").toLocaleLowerCase("pt-BR").includes(value)); }, [customers, query]);

  const save = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setPending(true); setNotice(null);
    const data = new FormData(event.currentTarget);
    try {
      const { error } = await supabase!.from("customers").insert({ name: String(data.get("name") || "").trim(), document_number: String(data.get("document_number") || "").replace(/\D/g, "") || null, phone: String(data.get("phone") || "").replace(/\D/g, "") || null });
      if (error) throw error;
      event.currentTarget.reset(); setOpenForm(false); setNotice({ tone: "success", message: "Cliente cadastrado com sucesso." }); await load();
    } catch (error) { setNotice({ tone: "error", message: `Não foi possível cadastrar o cliente: ${getErrorMessage(error)}` }); } finally { setPending(false); }
  };

  return <><ModuleHeader module="customers" action={<button onClick={() => setOpenForm((value) => !value)} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white"><Plus size={17} /> Novo cliente</button>} /><NoticeBanner notice={notice} />{openForm && <Panel className="mt-6"><form onSubmit={save} className="grid gap-4 md:grid-cols-3"><TextInput label="Nome do cliente" name="name" required placeholder="Nome completo" /><TextInput label="CPF/CNPJ" name="document_number" inputMode="numeric" placeholder="Somente números" /><TextInput label="Telefone" name="phone" inputMode="tel" placeholder="(67) 99999-9999" /><div className="md:col-span-3"><SubmitButton pending={pending}>Salvar cliente</SubmitButton></div></form></Panel>}<Panel className="mt-7"><label className="relative block"><Search className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por nome, CPF/CNPJ ou telefone" className="w-full rounded-2xl bg-slate-50 py-3 pl-11 pr-4 font-medium outline-none focus:ring-2 focus:ring-cyan-100" /></label><div className="mt-5 overflow-x-auto">{visible.length ? <table className="w-full min-w-[620px] text-left"><thead className="border-b border-slate-100 text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-3 py-3">Cliente</th><th className="px-3 py-3">Telefone</th><th className="px-3 py-3">CPF/CNPJ</th><th className="px-3 py-3">Cadastro</th></tr></thead><tbody className="divide-y divide-slate-100">{visible.map((customer) => <tr key={customer.id} className="text-sm"><td className="px-3 py-4 font-black">{customer.name}</td><td className="px-3 py-4 text-slate-600">{customer.phone || "—"}</td><td className="px-3 py-4 text-slate-600">{customer.document_number || "—"}</td><td className="px-3 py-4 text-slate-500">{formatDate(customer.created_at)}</td></tr>)}</tbody></table> : <EmptyState icon={Users} title="Nenhum cliente encontrado" description="Cadastre o primeiro cliente ou ajuste a busca acima." />}</div></Panel></>;
}

function QuotesModule({ customers }: { customers: Customer[] }) {
  const [quotes, setQuotes] = useState<Quote[]>([]);
  const [openForm, setOpenForm] = useState(false); const [pending, setPending] = useState(false); const [notice, setNotice] = useState<Notice>(null);
  const load = async () => { const { data, error } = await supabase!.from("quotes").select("id, title, event_date, total_amount, status, valid_until, customers(name)").order("created_at", { ascending: false }); if (error) throw error; setQuotes((data || []) as Quote[]); };
  useEffect(() => { load().catch((error) => setNotice({ tone: "error", message: `Não foi possível carregar os orçamentos: ${getErrorMessage(error)}` })); }, []);
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setPending(true); const data = new FormData(event.currentTarget); try { const { error } = await supabase!.from("quotes").insert({ title: String(data.get("title") || "").trim(), customer_id: String(data.get("customer_id") || "") || null, event_date: String(data.get("event_date") || "") || null, valid_until: String(data.get("valid_until") || "") || null, total_amount: Number(data.get("total_amount") || 0), status: "draft" }); if (error) throw error; event.currentTarget.reset(); setOpenForm(false); setNotice({ tone: "success", message: "Orçamento salvo como rascunho." }); await load(); } catch (error) { setNotice({ tone: "error", message: `Não foi possível salvar o orçamento: ${getErrorMessage(error)}` }); } finally { setPending(false); } };
  const styles: Record<string, string> = { draft: "bg-slate-100 text-slate-600", sent: "bg-cyan-100 text-cyan-800", approved: "bg-emerald-100 text-emerald-800", rejected: "bg-rose-100 text-rose-800", expired: "bg-amber-100 text-amber-800" };
  return <><ModuleHeader module="quotes" action={<button onClick={() => setOpenForm((value) => !value)} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white"><Plus size={17} /> Novo orçamento</button>} /><NoticeBanner notice={notice} />{openForm && <Panel className="mt-6"><form onSubmit={save} className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><TextInput label="Título" name="title" required placeholder="Ex.: Festa da Maria" /><SelectInput label="Cliente" name="customer_id"><option value="">Cliente ainda não cadastrado</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</SelectInput><TextInput label="Valor total" name="total_amount" type="number" min="0" step="0.01" defaultValue="0" required /><TextInput label="Data do evento" name="event_date" type="date" /><TextInput label="Válido até" name="valid_until" type="date" /><div className="flex items-end"><SubmitButton pending={pending}>Criar orçamento</SubmitButton></div></form></Panel>}<div className="mt-7 grid gap-4 xl:grid-cols-2">{quotes.length ? quotes.map((quote) => <Panel key={quote.id}><div className="flex items-start justify-between gap-3"><div><p className="font-black">{quote.title}</p><p className="mt-1 text-sm text-slate-500">{getCustomer(quote.customers)?.name || "Cliente a definir"}</p></div><span className={`rounded-full px-3 py-1 text-xs font-black ${styles[quote.status] || styles.draft}`}>{quote.status === "draft" ? "Rascunho" : quote.status}</span></div><div className="mt-5 flex items-end justify-between gap-3 border-t border-slate-100 pt-4"><p className="text-sm text-slate-500">Evento: <strong className="text-slate-700">{formatDate(quote.event_date)}</strong><br />Validade: <strong className="text-slate-700">{formatDate(quote.valid_until)}</strong></p><p className="text-xl font-black">{formatMoney(quote.total_amount)}</p></div></Panel>) : <div className="xl:col-span-2"><EmptyState icon={FileText} title="Nenhum orçamento cadastrado" description="Crie uma proposta para acompanhar seus atendimentos antes de confirmar uma reserva." /></div>}</div></>;
}

function FinanceModule() {
  const [entries, setEntries] = useState<FinancialEntry[]>([]); const [openForm, setOpenForm] = useState(false); const [pending, setPending] = useState(false); const [notice, setNotice] = useState<Notice>(null);
  const load = async () => { const { data, error } = await supabase!.from("financial_entries").select("id, description, category, entry_type, amount, due_date, paid_at, status").order("due_date", { ascending: true }); if (error) throw error; setEntries((data || []) as FinancialEntry[]); };
  useEffect(() => { load().catch((error) => setNotice({ tone: "error", message: `Não foi possível carregar o financeiro: ${getErrorMessage(error)}` })); }, []);
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setPending(true); const data = new FormData(event.currentTarget); try { const { error } = await supabase!.from("financial_entries").insert({ description: String(data.get("description") || "").trim(), category: String(data.get("category") || "").trim() || null, entry_type: String(data.get("entry_type")), amount: Number(data.get("amount") || 0), due_date: String(data.get("due_date") || "") || null, status: String(data.get("status")) }); if (error) throw error; event.currentTarget.reset(); setOpenForm(false); setNotice({ tone: "success", message: "Lançamento financeiro adicionado." }); await load(); } catch (error) { setNotice({ tone: "error", message: `Não foi possível adicionar o lançamento: ${getErrorMessage(error)}` }); } finally { setPending(false); } };
  const totals = entries.reduce((total, entry) => ({ income: total.income + (entry.entry_type === "income" ? Number(entry.amount) : 0), expense: total.expense + (entry.entry_type === "expense" ? Number(entry.amount) : 0) }), { income: 0, expense: 0 });
  return <><ModuleHeader module="finance" action={<button onClick={() => setOpenForm((value) => !value)} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white"><Plus size={17} /> Novo lançamento</button>} /><NoticeBanner notice={notice} /><div className="mt-7 grid gap-4 sm:grid-cols-3"><Panel><p className="text-sm font-bold text-slate-500">Entradas</p><p className="mt-2 text-3xl font-black text-emerald-600">{formatMoney(totals.income)}</p></Panel><Panel><p className="text-sm font-bold text-slate-500">Saídas</p><p className="mt-2 text-3xl font-black text-rose-600">{formatMoney(totals.expense)}</p></Panel><Panel><p className="text-sm font-bold text-slate-500">Resultado</p><p className="mt-2 text-3xl font-black">{formatMoney(totals.income - totals.expense)}</p></Panel></div>{openForm && <Panel className="mt-6"><form onSubmit={save} className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><TextInput label="Descrição" name="description" required placeholder="Ex.: Sinal da festa" /><TextInput label="Categoria" name="category" placeholder="Ex.: Locação" /><SelectInput label="Tipo" name="entry_type" defaultValue="income"><option value="income">Entrada</option><option value="expense">Saída</option></SelectInput><TextInput label="Valor" name="amount" type="number" min="0" step="0.01" required /><TextInput label="Vencimento" name="due_date" type="date" /><SelectInput label="Situação" name="status" defaultValue="pending"><option value="pending">Pendente</option><option value="paid">Pago</option><option value="overdue">Em atraso</option></SelectInput><div className="md:col-span-2 lg:col-span-3"><SubmitButton pending={pending}>Salvar lançamento</SubmitButton></div></form></Panel>}<Panel className="mt-7">{entries.length ? <div className="divide-y divide-slate-100">{entries.map((entry) => <article key={entry.id} className="flex flex-wrap items-center justify-between gap-4 py-4"><div><p className="font-black">{entry.description}</p><p className="mt-1 text-sm text-slate-500">{entry.category || "Sem categoria"} · Vencimento: {formatDate(entry.due_date)}</p></div><div className="text-right"><p className={`font-black ${entry.entry_type === "income" ? "text-emerald-600" : "text-rose-600"}`}>{entry.entry_type === "income" ? "+" : "−"} {formatMoney(entry.amount)}</p><p className="mt-1 text-xs font-bold uppercase text-slate-400">{entry.status === "paid" ? "Pago" : entry.status === "overdue" ? "Em atraso" : "Pendente"}</p></div></article>)}</div> : <EmptyState icon={WalletCards} title="Seu financeiro começa aqui" description="Adicione entradas e saídas para acompanhar o resultado da operação." />}</Panel></>;
}

function ContractsModule({ customers }: { customers: Customer[] }) {
  const [contracts, setContracts] = useState<Contract[]>([]); const [openForm, setOpenForm] = useState(false); const [pending, setPending] = useState(false); const [notice, setNotice] = useState<Notice>(null);
  const load = async () => { const { data, error } = await supabase!.from("contracts").select("id, title, status, signed_at, created_at, customers(name)").order("created_at", { ascending: false }); if (error) throw error; setContracts((data || []) as Contract[]); };
  useEffect(() => { load().catch((error) => setNotice({ tone: "error", message: `Não foi possível carregar os contratos: ${getErrorMessage(error)}` })); }, []);
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setPending(true); const data = new FormData(event.currentTarget); try { const { error } = await supabase!.from("contracts").insert({ title: String(data.get("title") || "").trim(), customer_id: String(data.get("customer_id") || "") || null, content: String(data.get("content") || ""), status: "draft" }); if (error) throw error; event.currentTarget.reset(); setOpenForm(false); setNotice({ tone: "success", message: "Contrato criado como rascunho." }); await load(); } catch (error) { setNotice({ tone: "error", message: `Não foi possível criar o contrato: ${getErrorMessage(error)}` }); } finally { setPending(false); } };
  return <><ModuleHeader module="contracts" action={<button onClick={() => setOpenForm((value) => !value)} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white"><Plus size={17} /> Novo contrato</button>} /><NoticeBanner notice={notice} />{openForm && <Panel className="mt-6"><form onSubmit={save} className="grid gap-4 md:grid-cols-2"><TextInput label="Título" name="title" required placeholder="Contrato de locação" /><SelectInput label="Cliente" name="customer_id"><option value="">Selecione depois</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</SelectInput><label className="md:col-span-2 block text-sm font-bold text-slate-700">Conteúdo do contrato<textarea name="content" rows={6} placeholder="Escreva ou cole aqui o texto-base do contrato." className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 font-medium outline-none focus:border-cyan-400 focus:ring-2 focus:ring-cyan-100" /></label><div className="md:col-span-2"><SubmitButton pending={pending}>Salvar contrato</SubmitButton></div></form></Panel>}<div className="mt-7 grid gap-4 xl:grid-cols-2">{contracts.length ? contracts.map((contract) => <Panel key={contract.id}><div className="flex items-start justify-between gap-3"><div><p className="font-black">{contract.title}</p><p className="mt-1 text-sm text-slate-500">{getCustomer(contract.customers)?.name || "Cliente a definir"}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black text-slate-600">{contract.status === "draft" ? "Rascunho" : contract.status === "signed" ? "Assinado" : contract.status}</span></div><p className="mt-5 border-t border-slate-100 pt-4 text-sm text-slate-500">Criado em {formatDate(contract.created_at)}{contract.signed_at ? ` · Assinado em ${formatDate(contract.signed_at)}` : ""}</p></Panel>) : <div className="xl:col-span-2"><EmptyState icon={FileCheck2} title="Nenhum contrato criado" description="Crie um rascunho para registrar a documentação de cada locação." /></div>}</div></>;
}

function ReceiptsModule({ customers }: { customers: Customer[] }) {
  const [receipts, setReceipts] = useState<Receipt[]>([]); const [openForm, setOpenForm] = useState(false); const [pending, setPending] = useState(false); const [notice, setNotice] = useState<Notice>(null);
  const load = async () => { const { data, error } = await supabase!.from("receipts").select("id, receipt_number, amount, issued_at, customers(name)").order("issued_at", { ascending: false }); if (error) throw error; setReceipts((data || []) as Receipt[]); };
  useEffect(() => { load().catch((error) => setNotice({ tone: "error", message: `Não foi possível carregar os recibos: ${getErrorMessage(error)}` })); }, []);
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setPending(true); const data = new FormData(event.currentTarget); try { const { error } = await supabase!.from("receipts").insert({ receipt_number: String(data.get("receipt_number") || "").trim(), customer_id: String(data.get("customer_id") || "") || null, amount: Number(data.get("amount") || 0), issued_at: String(data.get("issued_at") || "") || new Date().toISOString().slice(0, 10), notes: String(data.get("notes") || "").trim() || null }); if (error) throw error; event.currentTarget.reset(); setOpenForm(false); setNotice({ tone: "success", message: "Recibo registrado com sucesso." }); await load(); } catch (error) { setNotice({ tone: "error", message: `Não foi possível registrar o recibo: ${getErrorMessage(error)}` }); } finally { setPending(false); } };
  return <><ModuleHeader module="receipts" action={<button onClick={() => setOpenForm((value) => !value)} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white"><Plus size={17} /> Novo recibo</button>} /><NoticeBanner notice={notice} />{openForm && <Panel className="mt-6"><form onSubmit={save} className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><TextInput label="Número do recibo" name="receipt_number" required placeholder="REC-2026-001" /><SelectInput label="Cliente" name="customer_id"><option value="">Cliente a definir</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</SelectInput><TextInput label="Valor" name="amount" type="number" min="0" step="0.01" required /><TextInput label="Emissão" name="issued_at" type="date" defaultValue={new Date().toISOString().slice(0, 10)} /><label className="md:col-span-2 lg:col-span-4 block text-sm font-bold text-slate-700">Observação<input name="notes" className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 font-medium outline-none focus:border-cyan-400 focus:ring-2 focus:ring-cyan-100" /></label><div className="md:col-span-2 lg:col-span-4"><SubmitButton pending={pending}>Salvar recibo</SubmitButton></div></form></Panel>}<Panel className="mt-7">{receipts.length ? <div className="divide-y divide-slate-100">{receipts.map((receipt) => <article key={receipt.id} className="flex flex-wrap items-center justify-between gap-4 py-4"><div><p className="font-black">{receipt.receipt_number}</p><p className="mt-1 text-sm text-slate-500">{getCustomer(receipt.customers)?.name || "Cliente a definir"} · Emitido em {formatDate(receipt.issued_at)}</p></div><p className="text-xl font-black">{formatMoney(receipt.amount)}</p></article>)}</div> : <EmptyState icon={ReceiptText} title="Nenhum recibo emitido" description="Registre os recibos para manter os comprovantes centralizados." />}</Panel></>;
}

function AvailabilityModule() {
  const [blocks, setBlocks] = useState<AvailabilityBlock[]>([]); const [appointments, setAppointments] = useState<Appointment[]>([]); const [openForm, setOpenForm] = useState(false); const [pending, setPending] = useState(false); const [notice, setNotice] = useState<Notice>(null);
  const load = async () => { const [blocksResult, appointmentsResult] = await Promise.all([supabase!.from("availability_blocks").select("id, title, start_at, end_at, block_type").order("start_at", { ascending: true }), supabase!.from("appointments").select("id, event_date, start_time, end_time, status, customers(name)").in("status", ["confirmed", "draft"]).order("event_date", { ascending: true })]); if (blocksResult.error) throw blocksResult.error; if (appointmentsResult.error) throw appointmentsResult.error; setBlocks((blocksResult.data || []) as AvailabilityBlock[]); setAppointments((appointmentsResult.data || []) as Appointment[]); };
  useEffect(() => { load().catch((error) => setNotice({ tone: "error", message: `Não foi possível carregar a disponibilidade: ${getErrorMessage(error)}` })); }, []);
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setPending(true); const data = new FormData(event.currentTarget); try { const start = String(data.get("start_at") || ""); const end = String(data.get("end_at") || ""); if (!start || !end || end <= start) throw new Error("Informe um período válido para o bloqueio."); const { error } = await supabase!.from("availability_blocks").insert({ title: String(data.get("title") || "").trim(), block_type: String(data.get("block_type")), start_at: new Date(start).toISOString(), end_at: new Date(end).toISOString() }); if (error) throw error; event.currentTarget.reset(); setOpenForm(false); setNotice({ tone: "success", message: "Período bloqueado na disponibilidade." }); await load(); } catch (error) { setNotice({ tone: "error", message: `Não foi possível bloquear o período: ${getErrorMessage(error)}` }); } finally { setPending(false); } };
  return <><ModuleHeader module="availability" action={<button onClick={() => setOpenForm((value) => !value)} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white"><Plus size={17} /> Bloquear período</button>} /><NoticeBanner notice={notice} />{openForm && <Panel className="mt-6"><form onSubmit={save} className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><TextInput label="Motivo" name="title" required placeholder="Manutenção dos brinquedos" /><SelectInput label="Tipo" name="block_type"><option value="unavailable">Indisponível</option><option value="maintenance">Manutenção</option><option value="internal">Uso interno</option></SelectInput><TextInput label="Início" name="start_at" type="datetime-local" required /><TextInput label="Fim" name="end_at" type="datetime-local" required /><div className="md:col-span-2 lg:col-span-4"><SubmitButton pending={pending}>Bloquear agenda</SubmitButton></div></form></Panel>}<div className="mt-7 grid gap-6 xl:grid-cols-2"><Panel><div className="flex items-center gap-3"><CalendarDays className="text-[#00BFFF]" size={20} /><div><h2 className="font-black">Reservas na agenda</h2><p className="mt-1 text-sm text-slate-500">Eventos confirmados e rascunhos.</p></div></div><div className="mt-5 divide-y divide-slate-100">{appointments.length ? appointments.slice(0, 12).map((appointment) => <article key={appointment.id} className="py-4"><p className="font-black">{formatDate(appointment.event_date)} · {appointment.start_time?.slice(0, 5) || "Horário a definir"}</p><p className="mt-1 text-sm text-slate-500">{getCustomer(appointment.customers)?.name || "Cliente a definir"}</p></article>) : <p className="py-8 text-center text-sm text-slate-500">Nenhuma reserva agendada.</p>}</div></Panel><Panel><div className="flex items-center gap-3"><ClipboardList className="text-amber-500" size={20} /><div><h2 className="font-black">Bloqueios manuais</h2><p className="mt-1 text-sm text-slate-500">Períodos sem disponibilidade.</p></div></div><div className="mt-5 divide-y divide-slate-100">{blocks.length ? blocks.map((block) => <article key={block.id} className="py-4"><p className="font-black">{block.title}</p><p className="mt-1 text-sm text-slate-500">{new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(block.start_at))} até {new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(block.end_at))}</p></article>) : <p className="py-8 text-center text-sm text-slate-500">Nenhum bloqueio cadastrado.</p>}</div></Panel></div></>;
}

function StatisticsModule() {
  const [appointments, setAppointments] = useState<Appointment[]>([]); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState<Notice>(null);
  useEffect(() => { supabase!.from("appointments").select("id, event_date, total_amount, status, customers(id), appointment_items(quantity, products(name))").order("event_date", { ascending: false }).then(({ data, error }) => { if (error) setNotice({ tone: "error", message: `Não foi possível carregar as estatísticas: ${error.message}` }); else setAppointments((data || []) as Appointment[]); setLoading(false); }); }, []);
  const confirmed = appointments.filter((appointment) => appointment.status === "confirmed" || appointment.status === "completed"); const revenue = confirmed.reduce((total, appointment) => total + Number(appointment.total_amount || 0), 0); const average = confirmed.length ? revenue / confirmed.length : 0; const productCount = new Map<string, number>(); confirmed.forEach((appointment) => appointment.appointment_items?.forEach((item) => { const product = Array.isArray(item.products) ? item.products[0] : item.products; const name = product?.name || "Produto sem nome"; productCount.set(name, (productCount.get(name) || 0) + Number(item.quantity || 1)); })); const topProducts = [...productCount.entries()].sort((a, b) => b[1] - a[1]).slice(0, 5);
  return <><ModuleHeader module="statistics" /><NoticeBanner notice={notice} />{loading ? <div className="grid min-h-64 place-items-center"><LoaderCircle className="animate-spin text-[#00BFFF]" size={28} /></div> : <><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Panel><p className="text-sm font-bold text-slate-500">Reservas registradas</p><p className="mt-2 text-4xl font-black">{appointments.length}</p></Panel><Panel><p className="text-sm font-bold text-slate-500">Eventos concluídos ou confirmados</p><p className="mt-2 text-4xl font-black text-emerald-600">{confirmed.length}</p></Panel><Panel><p className="text-sm font-bold text-slate-500">Receita dos eventos</p><p className="mt-2 text-3xl font-black">{formatMoney(revenue)}</p></Panel><Panel><p className="text-sm font-bold text-slate-500">Ticket médio</p><p className="mt-2 text-3xl font-black">{formatMoney(average)}</p></Panel></div><Panel className="mt-7"><h2 className="font-black">Produtos mais reservados</h2><p className="mt-1 text-sm text-slate-500">Ranking calculado com base nos itens das reservas confirmadas e concluídas.</p>{topProducts.length ? <ol className="mt-6 divide-y divide-slate-100">{topProducts.map(([name, quantity], index) => <li key={name} className="flex items-center justify-between gap-4 py-4"><div className="flex items-center gap-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-cyan-50 text-sm font-black text-[#008fc0]">{index + 1}</span><p className="font-black">{name}</p></div><p className="font-black">{quantity} {quantity === 1 ? "unidade" : "unidades"}</p></li>)}</ol> : <EmptyState icon={BarChart3} title="Ainda não há dados suficientes" description="As estatísticas aparecerão assim que houver reservas confirmadas." />}</Panel></>}</>;
}

function CompanyModule() {
  const [company, setCompany] = useState<Record<string, string>>({}); const [pending, setPending] = useState(false); const [notice, setNotice] = useState<Notice>(null);
  useEffect(() => { supabase!.from("company_profiles").select("*").eq("id", true).maybeSingle().then(({ data, error }) => { if (error) setNotice({ tone: "error", message: `Não foi possível carregar os dados da empresa: ${error.message}` }); else if (data) setCompany(data as Record<string, string>); }); }, []);
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setPending(true); const data = new FormData(event.currentTarget); const payload: Record<string, string | null> = {}; data.forEach((value, key) => { payload[key] = String(value).trim() || null; }); try { const { error } = await supabase!.from("company_profiles").upsert({ id: true, ...payload }); if (error) throw error; setNotice({ tone: "success", message: "Dados da empresa atualizados." }); } catch (error) { setNotice({ tone: "error", message: `Não foi possível salvar os dados: ${getErrorMessage(error)}` }); } finally { setPending(false); } };
  return <><ModuleHeader module="company" /><NoticeBanner notice={notice} /><Panel className="mt-7"><form key={company.updated_at || "new-company"} onSubmit={save} className="grid gap-4 md:grid-cols-2"><TextInput label="Nome fantasia" name="trade_name" required defaultValue={company.trade_name || "Monteiro Locações"} /><TextInput label="Razão social" name="legal_name" defaultValue={company.legal_name || ""} /><TextInput label="CNPJ" name="document_number" defaultValue={company.document_number || ""} /><TextInput label="E-mail" name="email" type="email" defaultValue={company.email || ""} /><TextInput label="Telefone" name="phone" defaultValue={company.phone || ""} /><TextInput label="WhatsApp" name="whatsapp" defaultValue={company.whatsapp || ""} /><TextInput label="Endereço" name="address" defaultValue={company.address || ""} /><TextInput label="Cidade" name="city" defaultValue={company.city || ""} /><TextInput label="Estado" name="state" defaultValue={company.state || ""} /><TextInput label="CEP" name="postal_code" defaultValue={company.postal_code || ""} /><div className="md:col-span-2 mt-2"><SubmitButton pending={pending}>Salvar dados da empresa</SubmitButton></div></form></Panel></>;
}

function useAdminAccess() {
  const [ready, setReady] = useState(false); const [allowed, setAllowed] = useState(false);
  useEffect(() => { if (!supabase) { setAllowed(false); setReady(true); return undefined; } let active = true; supabase.auth.getSession().then(async ({ data }) => { if (!data.session) { if (active) { setAllowed(false); setReady(true); } return; } const { data: admin } = await supabase.from("admin_users").select("user_id").eq("user_id", data.session.user.id).maybeSingle(); if (active) { setAllowed(Boolean(admin)); setReady(true); } }); return () => { active = false; }; }, []);
  return { ready, allowed };
}

export default function CrmModule({ module }: { module: CrmModuleKey }) {
  const { ready, allowed } = useAdminAccess(); const [customers, setCustomers] = useState<Customer[]>([]);
  useEffect(() => { if (!supabase || !["quotes", "contracts", "receipts"].includes(module)) return; supabase.from("customers").select("id, name, document_number, phone, created_at").order("name").then(({ data }) => setCustomers((data || []) as Customer[])); }, [module]);
  if (!isSupabaseConfigured) return <main className="grid min-h-screen place-items-center p-5">Configure o Supabase para usar este módulo.</main>;
  if (!ready) return <main className="grid min-h-screen place-items-center"><LoaderCircle className="animate-spin text-[#00BFFF]" size={28} /></main>;
  if (!allowed) return <main className="grid min-h-screen place-items-center p-5"><Link to="/admin" className="rounded-xl bg-slate-950 px-5 py-3 font-bold text-white">Acesse o painel como administrador</Link></main>;
  return <AdminWorkspace><div className="mx-auto max-w-7xl">{module === "customers" && <CustomersModule />}{module === "quotes" && <QuotesModule customers={customers} />}{module === "finance" && <FinanceModule />}{module === "contracts" && <ContractsModule customers={customers} />}{module === "receipts" && <ReceiptsModule customers={customers} />}{module === "availability" && <AvailabilityModule />}{module === "statistics" && <StatisticsModule />}{module === "company" && <CompanyModule />}</div></AdminWorkspace>;
}
